### ISSUE TITLE
Bizarre behaviour of dynamically generated <a> tags with target=_blank

### ISSUE THREAD

**Issue by jgonggrijp** [UUDigitalHumanitieslab/daycare-ethics#3]
@mhkuu @cowl I would be grateful if you could have a look at this.

In order to inspect the problem for yourself, it suffices to download the tip of the `release/1.0` branch and open the inner `daycare_ethics/www/index.html` in Firefox. In fact just a copy of the `www` directory should be sufficient. No local webserver required, the application automatically connects to `https://doordenkertjes.hum.uu.nl`. No mobile device emulator required either, it happens right there in your browser.

The application has two pages with external links: the one with id `#about` (navigation from within app: Extra > Colofon) and the one with id `#links-tips` (navigation: Extra > Links en tips). In both pages, the external links are regular `<a>` tags with `target="_blank"`. However, in `#about` the links are present in the source HTML while in `#links-tips` they are dynamically generated in JavaScript. The latter seem to fail for this reason. A new browser tab does appear, but the URL does not load. The tab remains empty (`about:blank`). This happens in Safari and Firefox, as well as in iOS and Android webviews (in the latter two cases wrapped by PhoneGap and mediated by the in-app browser). 

I have been pulling my hair out for the reason why this is happening. It does not appear to be a common problem when I search the web. No error messages appear in the JavaScript console. The in-app browser on iOS does mention an "error" but without any further information. The Sources tab in the Safari inspector of the new empty tab also mentions that there was an error during loading, but nothing else. When inspecting the DOM on the main window, there appear to be no important differences between the external links in `#about` and those in `#links-tips`. If I intercept the click event and manually create a new tab for the referenced URL using `window.open`, the problem still exists (this is always the case with the in-app browser on the mobile platforms).

To make things even more curious, sometimes (I estimate about once in every 30 attempts) an external link from `#links-tips` *does* load successfully in the new tab or in-app browser. So apparently the intended behaviour is not impossible but "hard" enough to fail most of the time.

Note that you cannot test the application with Chrome. Chrome has overly restrictive security measures which prevent jQuery Mobile from booting completely, so you'll be looking at a spinning wheel forever. Fortunately this problem does not exist in the Android webview.

**Comment by mhkuu** [comment]
Hi @jgonggrijp! With me (Windows 10, Firefox 43.04) the success rate is about 50%, which is somewhat better than your 3% :-)

If I inspect the page I see that for the links in `#links-tips`, other than with the links in `#about`, there's actually two bound events; one default to jQuery, but also a call to the function `catchExternalLinks`. If I remove that, the URL is always opened correctly, so I suppose something is wrong there. Googling "event target href javascript" leads to http://stackoverflow.com/questions/8535218/jquery-target-href-with-a-href-img-a, which seems to be similar behaviour to what you're reporting. If I apply the proposed change there, it seems to work (on my machine, YMMV). Hope this helps!

**Comment by jgonggrijp** [comment]
Yes, this fixed it. I just needed to replace `event.target.href` with `this.href`. Thanks a lot!

I was actually making two mistakes. The first one was that I didn't realize the event target isn't necessarily the `<a>` element. The second one is that I didn't realize that `catchExternalLinks` is always enabled on `#links-tips`. This is the kind of silly mistake that makes you want to beat yourself with your keyboard. ;-)

This ticket also illustrates really well why a second pair of eyes is a good idea.
